import { BlogPost } from '../index';
import content from '../markdown/ai-shift-left-security-part1.md?raw';

export const blogPost: BlogPost = {
  slug: "ai-shift-left-security-part1",
  title: "From Bottleneck to Accelerator: AI Security Problem & Solution (Part 1)",
  subtitle: "The strategic problem every company faces and how AI automation eliminates the false choice between speed and security",
  excerpt: "Discover how AI automation transforms security from a bottleneck into an accelerator. Real-world case studies, proven tools, and the strategic solution to the speed vs security dilemma with global applicability.",
  content,
  publishDate: "2025-10-18",
  categories: ["AI Security", "DevSecOps", "Security Integration", "Shift Left Security"],
  searchCategories: ["DevSecOps"],
  featured: false,
  coverImage: "/blog/blogImages/ai-security-shift-left.png",
  coverImageCredit: "Generated by AI"
};
