import { BlogPost } from '../index';
import content from '../markdown/ai-shift-left-security.md?raw';

export const blogPost: BlogPost = {
  slug: "ai-shift-left-security",
  title: "From Bottleneck to Accelerator: How AI Automation Enables True Shift Left Security",
  subtitle: "Complete 6-layer enterprise security with global compliance - from network to AI models",
  excerpt: "AI automation transforms security from a bottleneck into an accelerator. Complete 6-layer enterprise security stack with global compliance (GDPR, CCPA, LGPD, PIPEDA), database encryption, AI model protection, and real-time threat detection.",
  content,
  publishDate: "2025-10-18",
  categories: ["AI Security", "DevSecOps", "Enterprise Security", "Global Compliance"],
  searchCategories: ["DevSecOps"],
  featured: true,
  coverImage: "/blog/blogImages/ai-security-shift-left.png",
  coverImageCredit: "Generated by AI"
};
