import { BlogPost } from '../index';
import content from '../markdown/ai-shift-left-security-part2.md?raw';

export const blogPost: BlogPost = {
  slug: "ai-shift-left-security-part2",
  title: "AI Security Implementation & Tools: Complete Guide (Part 2)",
  subtitle: "6-layer enterprise security implementation with global compliance, database protection, and AI model security",
  excerpt: "Complete 6-layer enterprise security implementation guide. Network security, WAF, SAST/DAST, identity management, database encryption, AI model protection, and global compliance (GDPR, CCPA, LGPD, PIPEDA).",
  content,
  publishDate: "2025-10-18",
  categories: ["AI Security", "DevSecOps", "Enterprise Security", "Implementation", "Global Compliance"],
  searchCategories: ["DevSecOps"],
  featured: false,
  coverImage: "/blog/blogImages/ai-security-shift-left.png",
  coverImageCredit: "Generated by AI"
};
