import { BlogPost } from '../index';
import content from '../markdown/ai-shift-left-security-part3.md?raw';

export const blogPost: BlogPost = {
  slug: "ai-shift-left-security-part3",
  title: "2025 AI Security Trends & Future: Complete Forecast (Part 3)",
  subtitle: "Global 2025 predictions, emerging threats, international regulations, and future-proof AI security strategies",
  excerpt: "Complete 2025 AI security forecast with global regulatory coverage (EU AI Act, US Executive Order, China AI Governance). Emerging threats, international compliance, and future-proof strategies for worldwide deployment.",
  content,
  publishDate: "2025-10-18",
  categories: ["AI Security", "Cybersecurity", "Future Trends", "Global Compliance"],
  searchCategories: ["DevSecOps"],
  featured: false,
  coverImage: "/blog/blogImages/ai-security-shift-left.png",
  coverImageCredit: "Generated by AI"
};
